language: node_js
node_js:
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g typescript
  - npm install tsd@next -g
  - npm install -g gulp
  - npm install -g ionic
  - npm install -g bower
  - npm install -g protractor
  - npm install -g cucumber
  - npm run setup
  - npm run update-webdriver
  - npm run travis-server > /dev/null &
  - npm run web-driver > /dev/null &
  - sleep 3 # give server time to start

script:
  - gulp
  - echo "Running unit tests..."
  - ./node_modules/karma/bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - echo "Running functional tests..."
  - protractor protractor.conf.js --browser=firefox
  - protractor cucumber.conf.js --browser=firefox
#  - cucumber.js -f=pretty